/* File generated by Đức's ClasHStamP */
using System;                                                   
using System.Collections.Generic;
using boolean = System.Boolean;
namespace Model {
    public  class Composition
    {
        public  Composition(
            int _attribute4
        ){
            attribute4 = _attribute4;
        }                                                                                       
        private int attribute4;                                 
    }
}
