#pragma once
/* File generated by Đức's ClasHStamP */
#include "Sensor.hpp"

const std::string Sensor::EventId_toString( Sensor::_EventId value ){
    switch( value ){
    case _EventId::evClearDataLatch: return std::string("evClearDataLatch");
    case _EventId::evDataComplete: return std::string("evDataComplete");
    case _EventId::evDataReady: return std::string("evDataReady");
    case _EventId::evHasNewData: return std::string("evHasNewData");
    case _EventId::evSensorReset: return std::string("evSensorReset");
    case _EventId::tm_100: return std::string("tm_100");
    default: return std::string("Sensor_UNKNOWN");
    }
}
