/* File generated by Đức's ClasHStamP */
package model;

import java.io.*;
import java.util.*;

public  class UsedDependency
{
    public  UsedDependency(
        int _attribute6
    ){
        attribute6 = _attribute6;
    }                                                                                           
    private int attribute6;                                     
}
