/* File generated by Đức's ClasHStamP */
package model;

import java.io.*;
import java.util.*;
import abstracts.*;

public  class Whip extends CondimentDecorator
{
    public double cost(
    ){
    	return .10 + beverage.cost();
    } /* Whip.cost */

    public String getDescription(){
        return beverage.getDescription() + ", Whip";

    }
    public  Whip(
        Beverage _beverage
    ) {
        super( _beverage );

    }                                                                                           
}
