/* File generated by Đức's ClasHStamP */
#define __AFriend_INTERNAL__
#include "CommonInclude.h"
#include "AFriend.h"
AFriend* AFriend_Copy( AFriend* pAFriend, const AFriend* pSource ){
    pAFriend->attribute3 = pSource->attribute3;
    return ( AFriend* )pAFriend;
}
