/* File generated by Đức's ClasHStamP */
package model;

import java.io.*;
import java.util.*;
import model.*;

public  class AFriend<T0, T1 extends Composition, T2, T3 extends Aggregration>
{
    public  AFriend(
        int _attribute3
    ){
        attribute3 = _attribute3;
    }                                                                                           
    private int attribute3;                                     
}
