/* File generated by Đức's ClasHStamP */
using System;                                                   
using System.Collections.Generic;
using boolean = System.Boolean;
using Abstracts;
namespace Model {
    public  class Whip: CondimentDecorator
    {
        public override double cost(
        ){
            return .10 + beverage.cost();
        } /* Whip.cost */

        public override String description {
            get{ return beverage.description + ", Whip"; }

        }
        public  Whip(
            Beverage _beverage
        ):  base( _beverage )
        {
        }                                                                                       
    }
}
