/* File generated by Đức's ClasHStamP */
package model;

import java.io.*;
import java.util.*;
import abstracts.*;

public  class Espresso extends Beverage
{
    public double cost(
    ){
    	return 1.99;
    } /* Espresso.cost */

    public  Espresso(
    ) {
        super( "Espresso" );

    }                                                                                           
}
