/* File generated by Đức's ClasHStamP */
package model;

import java.io.*;
import java.util.*;
import abstracts.*;

public  class HouseBlend extends Beverage
{
    public double cost(
    ){
    	return .89;
    } /* HouseBlend.cost */

    public  HouseBlend(
    ) {
        super( "House Blend" );

    }                                                                                           
}
