/* File generated by Đức's ClasHStamP */
using System;                                                   
using System.Collections.Generic;
using boolean = System.Boolean;
using Model;
namespace Model {
    public  class AFriend<T0, T1, T2, T3>
        where T1: Composition
        where T3: Aggregration
    {
        public  AFriend(
            int _attribute3
        ){
            attribute3 = _attribute3;
        }                                                                                       
        private int attribute3;                                 
    }
}
