#pragma once
/* File generated by Đức's ClasHStamP */
#include "Generic/CommonInclude.h"

class Interface1{
    public: void finalMethod(
    ){
    } /* Interface1.finalMethod */
    public:  Interface1(
    )
    {
    }                                                                                           
};
