#pragma once
/* File generated by Đức's ClasHStamP */
#include "ContextImpl.hpp"

const std::string ContextImpl::EventId_toString( ContextImpl::_EventId value ){
    switch( value ){
    case _EventId::E0: return std::string("E0");
    case _EventId::E1: return std::string("E1");
    case _EventId::E2: return std::string("E2");
    case _EventId::E3: return std::string("E3");
    case _EventId::E4: return std::string("E4");
    case _EventId::E5: return std::string("E5");
    default: return std::string("ContextImpl_UNKNOWN");
    }
}
