#pragma once
/* File generated by Đức's ClasHStamP */
#include "Generic/CommonInclude.h"

class Interface2{
    public: void methodWithParams(
        String parm1,
        float parm2
    ){
    } /* Interface2.methodWithParams */
    public:  Interface2(
    )
    {
    }                                                                                           
};
