#pragma once
/* File generated by Đức's ClasHStamP */
#include "Generic/CommonInclude.h"

class ObserverIfc{
    public: virtual void update(
        float temperature,
        float humidity,
        float pressure
    ) = 0;
    public:  ObserverIfc(
    )
    {
    }                                                                                           
};
