#pragma once
/* File generated by Đức's ClasHStamP */
#include "Generic/CommonInclude.h"

class CalledDependency{
    public:  CalledDependency(
        int _attribute0
    ): attribute0( _attribute0 )
    {
    }                                                                                           
    private: int attribute0;                                    
};
