#pragma once
/* File generated by Đức's ClasHStamP */
#include "Context.hpp"

int Context::classOrStaticAttribute;                            
std::vector<int> Context::initializedStaticArray = { 1, 2, 3 }; 
