/* File generated by Đức's ClasHStamP */
#define __AnyStatePtn_INTERNAL__
#include "CommonInclude.h"
#include "AnyStatePtn.h"
const TCHAR* AnyStatePtnEvent_toString( AnyStatePtn_EVENT value ){
    switch( value ){
    case AnyStatePtn_ev0: return _T( "ev0" );
    case AnyStatePtn_ev1: return _T( "ev1" );
    case AnyStatePtn_ev2: return _T( "ev2" );
    case AnyStatePtn_ev3: return _T( "ev3" );
    default: return _T( "AnyStatePtn_UNKNOWN" );
    }
}
static void AnyStateStm_BgnTrans( AnyStatePtn *pAnyStateTop, AnyStateStm* pStm, UINT32 targetState, UINT32 initState );
static void AnyStateStm_EndTrans( AnyStatePtn *pAnyStateTop, AnyStateStm* pStm );
static BOOL AnyStateStm_Reset( AnyStatePtn* pAnyStateTop, AnyStateStm* pStm, HdStateMachine* pParentStm, UINT32 nEntryPoint );
static BOOL AnyStateStm_Abort( AnyStatePtn* pAnyStateTop, AnyStateStm* pStm );
static BOOL AnyStateStm_EventProc( AnyStatePtn* pAnyStateTop, AnyStateStm* pStm, AnyStatePtn_EVENT nEventId, void* pEventParams );
static BOOL AnyStateStm_RunToCompletion( AnyStatePtn* pAnyStateTop, AnyStateStm* pStm );
static void AnyStateStm_CompositeState_Entry( AnyStatePtn* pAnyStatePtn, AnyStateStm* pStm ){
    if( HdStateMachine_Enterable( &pStm->base, AnyStateStm_CompositeState ) ){
        printf( "%s\n", __FUNCTION__ );
    }
}
static BOOL AnyStateStm_CompositeState_EventProc( AnyStatePtn* pAnyStatePtn, AnyStateStm* pStm, AnyStatePtn_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    pStm->base.nSourceState = AnyStateStm_CompositeState;
    switch( nEventId ){
    case AnyStatePtn_ev0:{
        AnyStateStm_BgnTrans( pAnyStatePtn, pStm, AnyStateStm_State0, STATE_UNDEF );
        AnyStateStm_EndTrans( pAnyStatePtn, pStm );
        bResult = TRUE;
    } break;
    case AnyStatePtn_ev1:{
        pStm->base.bIsExternTrans = TRUE;
        AnyStateStm_BgnTrans( pAnyStatePtn, pStm, AnyStateStm_State1, STATE_UNDEF );
        AnyStateStm_EndTrans( pAnyStatePtn, pStm );
        bResult = TRUE;
    } break;
    case AnyStatePtn_ev2:{
        pStm->base.bIsExternTrans = TRUE;
        AnyStateStm_BgnTrans( pAnyStatePtn, pStm, AnyStateStm_State2, STATE_UNDEF );
        AnyStateStm_EndTrans( pAnyStatePtn, pStm );
        bResult = TRUE;
    } break;
    case AnyStatePtn_ev3:{
        AnyStateStm_BgnTrans( pAnyStatePtn, pStm, AnyStateStm_State3, STATE_UNDEF );
        AnyStateStm_EndTrans( pAnyStatePtn, pStm );
        bResult = TRUE;
    } break;
    default: break;
    }
    return bResult;
}
static void AnyStateStm_CompositeState_Exit( AnyStatePtn* pAnyStatePtn, AnyStateStm* pStm ){
    if( HdStateMachine_Exitable( &pStm->base, AnyStateStm_CompositeState ) ){ 
        printf( "%s\n", __FUNCTION__ );
    }
}
static void AnyStateStm_State0_Entry( AnyStatePtn* pAnyStatePtn, AnyStateStm* pStm ){
    if( HdStateMachine_Enterable( &pStm->base, AnyStateStm_State0 ) ){
        AnyStateStm_CompositeState_Entry( pAnyStatePtn, pStm );
        printf( "%s\n", __FUNCTION__ );
    }
}
static BOOL AnyStateStm_State0_EventProc( AnyStatePtn* pAnyStatePtn, AnyStateStm* pStm, AnyStatePtn_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    pStm->base.nSourceState = AnyStateStm_State0;
    return bResult ? bResult : AnyStateStm_CompositeState_EventProc( pAnyStatePtn, pStm, nEventId, pEventParams );
}
static void AnyStateStm_State0_Exit( AnyStatePtn* pAnyStatePtn, AnyStateStm* pStm ){
    if( HdStateMachine_Exitable( &pStm->base, AnyStateStm_State0 ) ){ 
        printf( "%s\n", __FUNCTION__ );
        AnyStateStm_CompositeState_Exit( pAnyStatePtn, pStm );
    }
}
static void AnyStateStm_State1_Entry( AnyStatePtn* pAnyStatePtn, AnyStateStm* pStm ){
    if( HdStateMachine_Enterable( &pStm->base, AnyStateStm_State1 ) ){
        AnyStateStm_CompositeState_Entry( pAnyStatePtn, pStm );
        printf( "%s\n", __FUNCTION__ );
    }
}
static BOOL AnyStateStm_State1_EventProc( AnyStatePtn* pAnyStatePtn, AnyStateStm* pStm, AnyStatePtn_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    pStm->base.nSourceState = AnyStateStm_State1;
    return bResult ? bResult : AnyStateStm_CompositeState_EventProc( pAnyStatePtn, pStm, nEventId, pEventParams );
}
static void AnyStateStm_State1_Exit( AnyStatePtn* pAnyStatePtn, AnyStateStm* pStm ){
    if( HdStateMachine_Exitable( &pStm->base, AnyStateStm_State1 ) ){ 
        printf( "%s\n", __FUNCTION__ );
        AnyStateStm_CompositeState_Exit( pAnyStatePtn, pStm );
    }
}
static void AnyStateStm_State2_Entry( AnyStatePtn* pAnyStatePtn, AnyStateStm* pStm ){
    if( HdStateMachine_Enterable( &pStm->base, AnyStateStm_State2 ) ){
        AnyStateStm_CompositeState_Entry( pAnyStatePtn, pStm );
        printf( "%s\n", __FUNCTION__ );
    }
}
static BOOL AnyStateStm_State2_EventProc( AnyStatePtn* pAnyStatePtn, AnyStateStm* pStm, AnyStatePtn_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    pStm->base.nSourceState = AnyStateStm_State2;
    return bResult ? bResult : AnyStateStm_CompositeState_EventProc( pAnyStatePtn, pStm, nEventId, pEventParams );
}
static void AnyStateStm_State2_Exit( AnyStatePtn* pAnyStatePtn, AnyStateStm* pStm ){
    if( HdStateMachine_Exitable( &pStm->base, AnyStateStm_State2 ) ){ 
        printf( "%s\n", __FUNCTION__ );
        AnyStateStm_CompositeState_Exit( pAnyStatePtn, pStm );
    }
}
static void AnyStateStm_State3_Entry( AnyStatePtn* pAnyStatePtn, AnyStateStm* pStm ){
    if( HdStateMachine_Enterable( &pStm->base, AnyStateStm_State3 ) ){
        AnyStateStm_CompositeState_Entry( pAnyStatePtn, pStm );
        printf( "%s\n", __FUNCTION__ );
    }
}
static BOOL AnyStateStm_State3_EventProc( AnyStatePtn* pAnyStatePtn, AnyStateStm* pStm, AnyStatePtn_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    pStm->base.nSourceState = AnyStateStm_State3;
    return bResult ? bResult : AnyStateStm_CompositeState_EventProc( pAnyStatePtn, pStm, nEventId, pEventParams );
}
static void AnyStateStm_State3_Exit( AnyStatePtn* pAnyStatePtn, AnyStateStm* pStm ){
    if( HdStateMachine_Exitable( &pStm->base, AnyStateStm_State3 ) ){ 
        printf( "%s\n", __FUNCTION__ );
        AnyStateStm_CompositeState_Exit( pAnyStatePtn, pStm );
    }
}
static void AnyStateStm_EndTrans( AnyStatePtn *pAnyStatePtn, AnyStateStm* pStm ){
    pStm->base.nCurrentState = pStm->base.nTargetState;
    pStm->base.bIsExternTrans = FALSE;
    switch( pStm->base.nCurrentState ){
    case AnyStateStm_CompositeState:AnyStateStm_CompositeState_Entry( pAnyStatePtn, pStm ); break;
    case AnyStateStm_State0:    AnyStateStm_State0_Entry( pAnyStatePtn, pStm ); break;
    case AnyStateStm_State1:    AnyStateStm_State1_Entry( pAnyStatePtn, pStm ); break;
    case AnyStateStm_State2:    AnyStateStm_State2_Entry( pAnyStatePtn, pStm ); break;
    case AnyStateStm_State3:    AnyStateStm_State3_Entry( pAnyStatePtn, pStm ); break;
    default: break;
    }
}
static void AnyStateStm_BgnTrans( AnyStatePtn *pAnyStatePtn, AnyStateStm* pStm, UINT32 targetState, UINT32 initState ){
    pStm->base.nTargetState = targetState;
    pStm->base.nPseudostate = targetState;
    if( initState ){
        pStm->base.nPseudostate = initState;
    }
    switch( pStm->base.nCurrentState ){
    case AnyStateStm_CompositeState:AnyStateStm_CompositeState_Exit( pAnyStatePtn, pStm ); break;
    case AnyStateStm_State0:    AnyStateStm_State0_Exit( pAnyStatePtn, pStm ); break;
    case AnyStateStm_State1:    AnyStateStm_State1_Exit( pAnyStatePtn, pStm ); break;
    case AnyStateStm_State2:    AnyStateStm_State2_Exit( pAnyStatePtn, pStm ); break;
    case AnyStateStm_State3:    AnyStateStm_State3_Exit( pAnyStatePtn, pStm ); break;
    default: break;
    }
}
static BOOL AnyStateStm_StateDefaultTrans( AnyStatePtn* pAnyStatePtn, AnyStateStm* pStm ){
    BOOL bResult = FALSE;
    pStm->base.nSourceState = pStm->base.nCurrentState;
    pStm->base.nLCAState = STATE_UNDEF;
    do{   if( pStm->base.nCurrentState == AnyStateStm_AnyStateTop && pStm->base.nPseudostate == AnyStateStm_InitPt1 ){
        AnyStateStm_BgnTrans( pAnyStatePtn, pStm, AnyStateStm_CompositeState, AnyStateStm_InitPt2 );
        AnyStateStm_EndTrans( pAnyStatePtn, pStm );
        bResult = TRUE;
    }else if( pStm->base.nCurrentState == AnyStateStm_CompositeState && pStm->base.nPseudostate == AnyStateStm_InitPt2 ){
        AnyStateStm_BgnTrans( pAnyStatePtn, pStm, AnyStateStm_State0, STATE_UNDEF );
        AnyStateStm_EndTrans( pAnyStatePtn, pStm );
        bResult = TRUE;
    }else if( pStm->base.nCurrentState != pStm->base.nPseudostate && IS_IN(pStm->base.nPseudostate, AnyStateStm_AnyStateTop) ){
        AnyStateStm_BgnTrans( pAnyStatePtn, pStm, pStm->base.nPseudostate, STATE_UNDEF );
        AnyStateStm_EndTrans( pAnyStatePtn, pStm );
        bResult = TRUE;
    }else{
    }   }while( FALSE );
    return bResult;
}
static BOOL AnyStateStm_RunToCompletion( AnyStatePtn* pAnyStatePtn, AnyStateStm* pStm ){
    BOOL bResult;
    do{
        bResult = AnyStateStm_StateDefaultTrans( pAnyStatePtn, pStm );
    } while ( bResult );
    return bResult;
}
static BOOL AnyStateStm_Reset( AnyStatePtn* pAnyStatePtn, AnyStateStm* pStm, HdStateMachine* pParentStm, UINT32 nEntryPoint ) {
    pStm->base.pParentStm = pParentStm;
    if( nEntryPoint == NULL ){
        if( AnyStateStm_IsFinished( &pStm->base ) ){
            pStm->base.nPseudostate = AnyStateStm_InitPt1;
        }
    }else{
        if( AnyStateStm_IsFinished( &pStm->base ) ){
            pStm->base.nPseudostate = nEntryPoint;
            return FALSE;
        }else{
            pStm->base.nPseudostate = nEntryPoint;
        }
    }
    if( nEntryPoint != STATE_UNDEF && nEntryPoint <= STATE_TOP ){
    }
    return AnyStateStm_RunToCompletion( pAnyStatePtn, pStm );
}
static BOOL AnyStateStm_EventProc( AnyStatePtn* pAnyStatePtn, AnyStateStm* pStm, AnyStatePtn_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    pStm->base.nLCAState = STATE_UNDEF;
    switch( pStm->base.nCurrentState ){
    case AnyStateStm_CompositeState:            bResult |= AnyStateStm_CompositeState_EventProc( pAnyStatePtn, pStm, nEventId, pEventParams ); break;
    case AnyStateStm_State0:                    bResult |= AnyStateStm_State0_EventProc( pAnyStatePtn, pStm, nEventId, pEventParams ); break;
    case AnyStateStm_State1:                    bResult |= AnyStateStm_State1_EventProc( pAnyStatePtn, pStm, nEventId, pEventParams ); break;
    case AnyStateStm_State2:                    bResult |= AnyStateStm_State2_EventProc( pAnyStatePtn, pStm, nEventId, pEventParams ); break;
    case AnyStateStm_State3:                    bResult |= AnyStateStm_State3_EventProc( pAnyStatePtn, pStm, nEventId, pEventParams ); break;
    default: break;
    }
    AnyStateStm_RunToCompletion( pAnyStatePtn, pStm );
    return bResult;
}
static BOOL AnyStateStm_IsIn( AnyStateStm* pStm, UINT32 nCompositeState ) {
    if( IS_IN( pStm->base.nCurrentState, nCompositeState ) ){ return TRUE; }
    return FALSE;
}
static BOOL AnyStateStm_Abort( AnyStatePtn* pAnyStatePtn, AnyStateStm* pStm ) {
    pStm->base.nSourceState = AnyStateStm_AnyStateTop;
    AnyStateStm_BgnTrans( pAnyStatePtn, pStm, AnyStateStm_AnyStateTop, STATE_UNDEF );
    AnyStateStm_EndTrans( pAnyStatePtn, pStm );
    return TRUE;
}
int AnyStateStm_IsFinished(AnyStateStm* pAnyStateStm){
    return pAnyStateStm->base.nCurrentState == AnyStateStm_AnyStateTop && pAnyStateStm->base.nCurrentState == pAnyStateStm->base.nPseudostate;
}
Context* AnyStatePtn_Copy( AnyStatePtn* pAnyStatePtn, const AnyStatePtn* pSource ){
    Context_Copy( ( Context* )pAnyStatePtn, ( Context* )pSource );
    return ( Context* )pAnyStatePtn;
}
BOOL AnyStatePtn_EventProc( AnyStatePtn* pAnyStatePtn, AnyStatePtn_EVENT nEventId, void* pEventParams ){
    return AnyStateStm_EventProc( pAnyStatePtn, &pAnyStatePtn->mainStm, nEventId, pEventParams );
}
BOOL AnyStatePtn_Start( AnyStatePtn* pAnyStatePtn ){
    AnyStateStm_Abort( pAnyStatePtn, &pAnyStatePtn->mainStm );
    return AnyStateStm_Reset( pAnyStatePtn, &pAnyStatePtn->mainStm, NULL, STATE_UNDEF );
}
BOOL AnyStatePtn_IsIn( AnyStatePtn* pAnyStatePtn, UINT32 nState ){
    return AnyStateStm_IsIn( &pAnyStatePtn->mainStm, nState );
}
