/* File generated by Đức's ClasHStamP */
#define __CalledDependency_INTERNAL__
#include "CommonInclude.h"
#include "CalledDependency.h"
CalledDependency* CalledDependency_Copy( CalledDependency* pCalledDependency, const CalledDependency* pSource ){
    pCalledDependency->attribute0 = pSource->attribute0;
    return ( CalledDependency* )pCalledDependency;
}
