/* File generated by Đức's ClasHStamP */
#define __Composition_INTERNAL__
#include "CommonInclude.h"
#include "Composition.h"
Composition* Composition_Copy( Composition* pComposition, const Composition* pSource ){
    pComposition->attribute4 = pSource->attribute4;
    return ( Composition* )pComposition;
}
