#pragma once
/* File generated by Đức's ClasHStamP */
#include "Generic/CommonInclude.h"

class Interface2{
    public: virtual void operation2(
    ) = 0;
    public:  Interface2(
    )
    {
    }                                                                                           
};
