/* File generated by Đức's ClasHStamP */
#define __DarkRoast_INTERNAL__
#include "CommonInclude.h"
#include "DarkRoast.h"
/** @public @memberof DarkRoast */
static double DarkRoast_cost(
    DarkRoast* pDarkRoast
){
    return .99;
} /* DarkRoast_cost */

Beverage* DarkRoast_Copy( DarkRoast* pDarkRoast, const DarkRoast* pSource ){
    Beverage_Copy( ( Beverage* )pDarkRoast, ( Beverage* )pSource );
    return ( Beverage* )pDarkRoast;
}
const BeverageVtbl gDarkRoastVtbl = {
    .pcost                       = DarkRoast_cost,
};
