#pragma once
/* File generated by Đức's ClasHStamP */
#include "Generic/CommonInclude.h"
#include "Abstracts/Beverage.hpp"                               

class HouseBlend: public Beverage{
    public: virtual double cost(
    ){
        return .89;
    } /* HouseBlend.cost */
    friend class Main;
    public:  HouseBlend(
    ):  Beverage( "House Blend" )
    {
    }                                                                                           
};
