#pragma once
/* File generated by Đức's ClasHStamP */
#include "Generic/CommonInclude.h"
#include "Abstracts/CondimentDecorator.hpp"                     

class Whip: public CondimentDecorator{
    public: virtual double cost(
    ){
        return 0.10 + beverage->cost();
    } /* Whip.cost */
    protected: virtual String getDescription() const {
        return (String)beverage->m_description + ", Whip";
    };
    friend class Main;
    public:  Whip(
        Beverage *_beverage
    ):  CondimentDecorator( _beverage )
    {
    }                                                                                           
};
