/* File generated by Đức's ClasHStamP */
package model;

import java.io.*;
import java.util.*;

public  class Aggregration
{
    public  Aggregration(
        int _attribute2
    ){
        attribute2 = _attribute2;
    }                                                                                           
    private int attribute2;                                     
}
