/* File generated by Đức's ClasHStamP */
using System;                                                   
using System.Collections.Generic;
using boolean = System.Boolean;
namespace Abstracts {
    public  abstract class Beverage
    {
        public abstract double cost(
        );
        public virtual String description {
            get;
            set;
        }
        public  Beverage(
            String _description
        ){
            description = _description;
        }                                                                                       
    }
}
