/* File generated by Đức's ClasHStamP */
using System;                                                   
using System.Collections.Generic;
using boolean = System.Boolean;
using Abstracts;
namespace Abstracts {
    public  abstract class CondimentDecorator: Beverage
    {
        public  CondimentDecorator(
            Beverage _beverage
        ):  base( "Unknown Beverage" )
        {
            beverage = _beverage;
        }                                                                                       
        protected   Beverage beverage;                          
    }
}
