/* File generated by Đức's ClasHStamP */
package model;

import java.io.*;
import java.util.*;
import interfaces.*;

public  class CurrentConditionDisplay implements ObserverIfc
{
    public void update(
        float temperature,
        float humidity,
        float pressure
    ){
    	this.temperature = temperature;
    	this.humidity = humidity;
    	display();
    } /* CurrentConditionDisplay.update */

    public void display(
    ){
    	System.out.println("Current condition: " + temperature + "�� and " + humidity + "% humidity");
    } /* CurrentConditionDisplay.display */
    public  CurrentConditionDisplay(
        Subject _weatherData
    ){
        temperature = 0;
        humidity = 0;
        weatherData = _weatherData;
        weatherData.registerObserver(this);
    }                                                                                           
    private float temperature;                                  
    private float humidity;                                     
    private Subject weatherData;                                  
}
