/* File generated by Đức's ClasHStamP */
package model;

import java.io.*;
import java.util.*;
import interfaces.*;

public  class WeatherData implements Subject
{
    public void registerObserver(
        ObserverIfc o
    ){
    	observers.add(o);
    } /* WeatherData.registerObserver */

    public void removeObserver(
        ObserverIfc o
    ){
    	int i = observers.indexOf(o);
    	if (i >= 0) {
    		observers.remove(i);
    	}
    } /* WeatherData.removeObserver */

    public void notifyObserver(
    ){
    	for (int i = 0; i < observers.size(); i++) {
    		ObserverIfc observer = observers.get(i);
    		observer.update(temperature, humidity, pressure);    		
    	}
    } /* WeatherData.notifyObserver */

    public void measurementsChanged(
    ){
    	notifyObserver();
    } /* WeatherData.measurementsChanged */
    public void setMeasurements(
        float temperature,
        float humidity,
        float pressure
    ){
    	this.temperature = temperature;
    	this.humidity = humidity;
    	this.pressure = pressure;
    	measurementsChanged();
    } /* WeatherData.setMeasurements */
    float getTemperature(){
        return temperature;
    }
    float getHumidity(){
        return humidity;
    }
    float getPressure(){
        return pressure;
    }
    public  WeatherData(
    ){
        temperature = 0;
        humidity = 0;
        pressure = 0;
        observers = new ArrayList<ObserverIfc>();
    }                                                                                           
    private float temperature;                                  
    private float humidity;                                     
    private float pressure;                                     
    private ArrayList<ObserverIfc> observers;                      
}
