/* File generated by Đức's ClasHStamP */
package model;

import java.io.*;
import java.util.*;

public  class Context
{
    public  Context(
        int _attribute0
    ){
        attribute0 = _attribute0;
    }                                                                                           
    private int attribute0;                                     
}
