/* File generated by Đức's ClasHStamP */
using System;                                                   
using System.Collections.Generic;
using boolean = System.Boolean;
using Abstracts;
namespace Model {
    public  class DarkRoast: Beverage
    {
        public override double cost(
        ){
            return .99;
        } /* DarkRoast.cost */

        public  DarkRoast(
        ):  base( "Dark Roast" )
        {
        }                                                                                       
    }
}
