/* File generated by Đức's ClasHStamP */
using System;                                                   
using System.Collections.Generic;
using boolean = System.Boolean;
using Abstracts;
namespace Model {
    public  class HouseBlend: Beverage
    {
        public override double cost(
        ){
            return .89;
        } /* HouseBlend.cost */

        public  HouseBlend(
        ):  base( "House Blend" )
        {
        }                                                                                       
    }
}
