#pragma once
/* File generated by Đức's ClasHStamP */
#include "Generic/CommonInclude.h"

class BaseClass{
    public: virtual void virtualFunc(
        int param0
    ) = 0;
    public:  BaseClass(
    )
    {
    }                                                                                           
};
