#pragma once
/* File generated by Đức's ClasHStamP */
#include "Generic/CommonInclude.h"

class UsedDependency{
    public:  UsedDependency(
        int _attribute1
    ): attribute1( _attribute1 )
    {
    }                                                                                           
    private: int attribute1;                                    
};
