/* File generated by Đức's ClasHStamP */
using System;                                                   
using System.Collections.Generic;
using boolean = System.Boolean;
namespace Model {
    public  class UsedDependency
    {
        public  UsedDependency(
            int _attribute6
        ){
            attribute6 = _attribute6;
        }                                                                                       
        private int attribute6;                                 
    }
}
