/* File generated by Đức's ClasHStamP */
#define __Subject_INTERNAL__
#include "CommonInclude.h"
#include "Subject.h"
/** @public @pure @memberof Subject */
void Subject_registerObserver(
    Subject* pSubject,
    ObserverIfc* o
){
    if( pSubject->vTbl == NULL || pSubject->vTbl->pregisterObserver == NULL ){ return; }
    pSubject->vTbl->pregisterObserver( pSubject, o );
} /* Subject_registerObserver */

/** @public @pure @memberof Subject */
void Subject_removeObserver(
    Subject* pSubject,
    ObserverIfc* o
){
    if( pSubject->vTbl == NULL || pSubject->vTbl->premoveObserver == NULL ){ return; }
    pSubject->vTbl->premoveObserver( pSubject, o );
} /* Subject_removeObserver */

/** @public @pure @memberof Subject */
void Subject_notifyObserver(
    Subject* pSubject
){
    if( pSubject->vTbl == NULL || pSubject->vTbl->pnotifyObserver == NULL ){ return; }
    pSubject->vTbl->pnotifyObserver( pSubject );
} /* Subject_notifyObserver */

Subject* Subject_Copy( Subject* pSubject, const Subject* pSource ){
    return ( Subject* )pSubject;
}
