/* File generated by Đức's ClasHStamP */
using System;                                                   
using System.Collections.Generic;
using boolean = System.Boolean;
namespace Model {
    public  class Aggregration
    {
        public  Aggregration(
            int _attribute2
        ){
            attribute2 = _attribute2;
        }                                                                                       
        private int attribute2;                                 
    }
}
