#pragma once
/* File generated by Đức's ClasHStamP */
#include "Generic/CommonInclude.h"
#include "Abstracts/Beverage.hpp"                               

class DarkRoast: public Beverage{
    public: virtual double cost(
    ){
        return .99;
    } /* DarkRoast.cost */
    friend class Main;
    public:  DarkRoast(
    ):  Beverage( "Dark Roast" )
    {
    }                                                                                           
};
