/* File generated by Đức's ClasHStamP */
#define __BaseClass_INTERNAL__
#include "CommonInclude.h"
#include "BaseClass.h"
/** @public @pure @memberof BaseClass */
void BaseClass_publicMethod(
    BaseClass* pBaseClass
){
    if( pBaseClass->vTbl == NULL || pBaseClass->vTbl->ppublicMethod == NULL ){ return; }
    pBaseClass->vTbl->ppublicMethod( pBaseClass );
} /* BaseClass_publicMethod */

/** @public @pure @memberof BaseClass */
void BaseClass_protectedMethod(
    BaseClass* pBaseClass
){
    if( pBaseClass->vTbl == NULL || pBaseClass->vTbl->pprotectedMethod == NULL ){ return; }
    pBaseClass->vTbl->pprotectedMethod( pBaseClass );
} /* BaseClass_protectedMethod */

/** @protected @pure @memberof BaseClass */
void BaseClass_packageVisibleMethod(
    BaseClass* pBaseClass
){
    if( pBaseClass->vTbl == NULL || pBaseClass->vTbl->ppackageVisibleMethod == NULL ){ return; }
    pBaseClass->vTbl->ppackageVisibleMethod( pBaseClass );
} /* BaseClass_packageVisibleMethod */

BaseClass* BaseClass_Copy( BaseClass* pBaseClass, const BaseClass* pSource ){
    return ( BaseClass* )pBaseClass;
}
