/* File generated by Đức's ClasHStamP */
#define __Context_INTERNAL__
#include "CommonInclude.h"
#include "Context.h"
#include "CalledDependency.h"                                   
/** @private @static @memberof Context */
static int classOrStaticAttribute;                              
/** @private @static @memberof Context */
static int initializedStaticArray[   ] = { 1, 2, 3 };           
/** @private @static @memberof Context */
static const int finalConstantAttribute = 5;                    
void Context_classOrStaticMethod(

){
} /* Context_classOrStaticMethod */

/** @public @memberof Context */
static void Context_publicMethod(
    Context* pContext
){
} /* Context_publicMethod */

/** @private @memberof Context */
static void Context_privateLeafMethod(
    Context* pContext
){
} /* Context_privateLeafMethod */

/** @public @memberof Context */
 Context_Context(
    Context* pContext
){
} /* Context_Context */

/** @public @memberof Context */
void Context_methodWithParams(
    Context* pContext,
    String parm1,
    float parm2
){
} /* Context_methodWithParams */

/** @public @memberof Context */
UsedDependency* Context_methodReturnsSomething(
    Context* pContext
){
} /* Context_methodReturnsSomething */

/** @public @memberof Context */
void Context_methodThrowsException(
    Context* pContext
){
} /* Context_methodThrowsException */

/** @public @memberof Context */
void Context_finalMethod(
    Context* pContext
){
} /* Context_finalMethod */

/** @protected @memberof Context */
static void Context_protectedMethod(
    Context* pContext
){
} /* Context_protectedMethod */

/** @protected @memberof Context */
static void Context_packageVisibleMethod(
    Context* pContext
){
} /* Context_packageVisibleMethod */

BaseClass* Context_Copy( Context* pContext, const Context* pSource ){
    BaseClass_Copy( ( BaseClass* )pContext, ( BaseClass* )pSource );
    pContext->publicAttribute = pSource->publicAttribute;
    pContext->privateAttribute = pSource->privateAttribute;
    pContext->internalAttribute = pSource->internalAttribute;
    pContext->isInitializedAttribute = pSource->isInitializedAttribute;
    memcpy( pContext->anAggregation, pSource->anAggregation, sizeof( pContext->anAggregation ) );
    memcpy( pContext->aProtectedComposition, pSource->aProtectedComposition, sizeof( pContext->aProtectedComposition ) );
    return ( BaseClass* )pContext;
}
const BaseClassVtbl gContextVtbl = {
    .ppublicMethod               = Context_publicMethod,
    .pprotectedMethod            = Context_protectedMethod,
    .ppackageVisibleMethod       = Context_packageVisibleMethod,
};
