/* File generated by Đức's ClasHStamP */
#define __UsedDependency_INTERNAL__
#include "CommonInclude.h"
#include "UsedDependency.h"
UsedDependency* UsedDependency_Copy( UsedDependency* pUsedDependency, const UsedDependency* pSource ){
    pUsedDependency->attribute6 = pSource->attribute6;
    return ( UsedDependency* )pUsedDependency;
}
