/* File generated by Đức's ClasHStamP */
package abstracts;

import java.io.*;
import java.util.*;

public  abstract class Beverage
{
    public abstract double cost(
    );
    public String getDescription(){
        return description;
    }
    public void setDescription(String value){
        description = value;
    }
    public  Beverage(
        String _description
    ){
        description = _description;
    }                                                                                           
    public String description;                                  
}
