#pragma once
/* File generated by Đức's ClasHStamP */
#include "AirspeedSensor.hpp"

const std::string AirspeedSensor::EventId_toString( AirspeedSensor::_EventId value ){
    switch( value ){
    case _EventId::evDataReady: return std::string("evDataReady");
    case _EventId::evDisablePolling: return std::string("evDisablePolling");
    case _EventId::evEnablePolling: return std::string("evEnablePolling");
    case _EventId::evFinish: return std::string("evFinish");
    case _EventId::evStart: return std::string("evStart");
    case _EventId::evStop: return std::string("evStop");
    case _EventId::tm_POLLTIME: return std::string("tm_POLLTIME");
    default: return std::string("AirspeedSensor_UNKNOWN");
    }
}
