#pragma once
/* File generated by Đức's ClasHStamP */
#include "AnyStatePtn.hpp"

const std::string AnyStatePtn::EventId_toString( AnyStatePtn::_EventId value ){
    switch( value ){
    case _EventId::ev0: return std::string("ev0");
    case _EventId::ev1: return std::string("ev1");
    case _EventId::ev2: return std::string("ev2");
    case _EventId::ev3: return std::string("ev3");
    default: return std::string("AnyStatePtn_UNKNOWN");
    }
}
